### ISSUE TITLE
没有readme么，请问怎么初始化sqlite数据库啊。

### ISSUE THREAD

**Issue by burnegg** [fengyouchao/webzmap#1]
安装后，addsuperuser 和登陆的时候都提示没有表auth_user 。应该是没有初始化数据库吧？

**Comment by burnegg** [comment]
好吧，运行startserver 有提示。应该是运行python manage.py migrate

**Comment by burnegg** [comment]
还有个问题是，createsuperuser的时候，提示输入用户名，然后输入回车没用，感觉是回车被当作一个不可见字符处理了

**Comment by burnegg** [comment]
好像是django的问题，把djongo的addsuperuser.py中182换成
raw_value = raw_input(message)
成功解决

**Comment by burnegg** [comment]
添加任务后一直处于pending状态。。。

**Comment by fengyouchao** [comment]
不好意思，目前项目还没空更新，空了会补上readme
初始化数据库
`python manage.py migrate`
创建管理员
`python manage.py createsuperuser`
创建crontab任务
`sudo python manage.py crontab add`
运行
`python manage.py runserver`
访问http://localhost:8000

**Comment by fengyouchao** [comment]
已经加上了README
